package org.wastingnotime.contactsmobile.infrastructure.config

typealias ContactsApiBaseUrlConfiguration = ContactsBffBaseUrlConfiguration
typealias ContactsApiBaseUrlResolver = ContactsBffBaseUrlResolver
